version: '2'

services:

    db:
      image: postgres:9.6.1
      container_name: db_rest
      restart: always
      ports:
        - "5432:5432"
      volumes:
       - "./postgres/data:/var/lib/postgresql/data"
      networks:
        - code-network
    web:
        image: nginx:latest
        container_name: nginx_rest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - "php"
        networks:
            - code-network
    php:
        image: denwood/php-fpm-with-postgres-connector
        container_name: php_rest
        restart: always
        volumes:
            - ./code:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
